### ISSUE TITLE
Deploy Qiskit onto a Raspberry Pi (emulator if device not available)

### ISSUE THREAD

**Issue by robertloredo** [qiskit-community/qiskit-camp-africa-19#11]
# Abstract

Many educators and makers are interested in using Raspberry Pi devices as a teaching tool or creating fun projects for students and hobbyists. Having the ability to load Qiskit onto a Raspberry Pi device may be an ideal project. 

# Description 

Load Qiskit onto a Raspberry Pi (emulator if hardware not available) that can take data input and run a quantum experiment. For example: read in a musical note and output a harmonized note. Extra credit if includes changes in Key signatures! 

**Challenge** use interference as a means to determine an ideal chord, given the root note (or any other data) as input. 

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @robertloredo 

# Deliverable

# GitHub repo

**Comment by HuangJunye** [comment]
I found a repo with similar idea: https://github.com/ordmoj/qrasp

**Comment by quantumjim** [comment]
@asierarranz will there be a raspi at the camp?

**Comment by willie84** [comment]
This looks super interesting. 
This is wonderful.

**Comment by bytesalad** [comment]
Looks like an interesting project

**Comment by robertloredo** [comment]
A link with a similar deployment:
https://github.com/kproche/quantum-raspberry-tie
