### ISSUE TITLE
Implement new classical optimizer for VQE/QAOA

### ISSUE THREAD

**Issue by BryceFuller** [qiskit-community/qiskit-camp-africa-19#14]
# Abstract
 An interesting optimizer has been proposed recently by Stokes et al which shows promise for use in VQE. Let’s implement it and test how well it works with stochastic noise!

![image](https://user-images.githubusercontent.com/22630711/70606902-225b1f00-1c06-11ea-9ae2-e9fc322063a0.png)

[This paper](https://arxiv.org/abs/1909.02108) goes into a lot of detail about it. 

[This paper](https://arxiv.org/abs/1909.05074) helps explain the approach more intuitively.

[This blog post from Xanadu](https://pennylane.ai/qml/app/tutorial_quantum_natural_gradient.html) is also very useful. (it's also where I took the above image from)

[Xanadu's pennylane platform has an implementation of this optimizer](https://github.com/XanaduAI/pennylane/blob/master/pennylane/optimize/qng.py); however, pennylane is set up differently than qiskit-so it will not be a copy-paste situation. 

# Members

 - Qiskit Coach: {githhub: @BryceFuller, slack: @Bryce Fuller}

# Deliverable
An optimizer module that we can use within qiskit. Some pretty graphs showing how well our optimizer performs under stochastic noise. 

# GitHub repo

**Comment by buriom** [comment]
Looks interesting
