### ISSUE TITLE
Quantum Music Loops

### ISSUE THREAD

**Issue by JavaFXpert** [qiskit-community/qiskit-camp-africa-19#16]
# Abstract
Create a musical loop generator that generates a “loop” by running a circuit 2^num_qubit times and playing the measured note pitch each time. The input to the circuit would be an incrementing basis state (e.g. |000> through |111>. The musician would control the output by altering the circuit before the next loop is generated.

For starters could use a three qubit circuit, with each basis state representing a pitch in a diatonic scale. A circuit with no gates would generate an ascending major scale. A circuit with three X gates would generate a descending major scale.   Rotations and entanglement would allow nature to participate with the musician in the creative process.

As a stretch goal, take the same approach with rhythms, generating note duration values that the generated notes will have.

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @omarcostahamido

# Deliverable
An app that creates loops in real-time as described above. Capability for updating the quantum circuit needs to be created, but perhaps in a very rudimentary form given the timeframe of the hackathon.

# GitHub repo

**Comment by oliverfunk** [comment]
@qcamp
Would like to join this project

**Comment by bytesalad** [comment]
I am interested in this project. My expertise is in software engineering but I also have background as a musician.
