### ISSUE TITLE
Calibration Routines with OpenPulse

### ISSUE THREAD

**Issue by nbronn** [qiskit-community/qiskit-camp-africa-19#29]
# Abstract

Use OpenPulse to develop qubit calibration routines.

# Description 

Calibration routines require pulse-level access to the qubits in order to determine the correct frequency, amplitude, etc, for creating native gates such as X90 and CNOT gates. Some techniques from the scientific literature that would be interesting to implement are
- Parameter determination from error amplification ([here](https://arxiv.org/abs/1504.06597))
- Hamiltonian tomography to determine and correct interaction terms in the cross resonance gate ([here](https://arxiv.org/abs/1603.04821))
- The effect of spectator qubits on cross resonance ([here](https://arxiv.org/abs/1605.01351))

# Members

 - @nbronn 
 - Qiskit Coach: @nbronn 

# Deliverable

# GitHub repo

**Comment by 1ucian0** [comment]
@qcamp

**Comment by conradhaupt** [comment]
This looks very interesting!
