### ISSUE TITLE
Quantum Circuit Optimisation using SAT solver & A* Algorithm

### ISSUE THREAD

**Issue by fifimatu** [qiskit-community/qiskit-camp-africa-19#37]
# Abstract
Find the optimal SWAP gates  necessary for running a quantum circuit on the IBM Q system using SAT solver to find the best qubit placement and the A* algorithm to find the minimum SWAP gates between sub-circuits

This project will implement Atsushi Matsuo et al's algorithm: 

Reducing the Overhead of Mapping Quantum Circuits to IBM Q System
https://ieeexplore.ieee.org/document/8702439

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@Fiona Matu`
 - Qiskit Coach: @fifimatu 

# Deliverable
Terra module

# GitHub repo

**Comment by 1ucian0** [comment]
Maybe you want to have a look to: 
 - https://github.com/Qiskit/qiskit-terra/pull/1310
 - https://github.com/Qiskit/qiskit-terra/pull/3586#pullrequestreview-330268808
 - and the results of  https://github.com/qiskit-community/qiskit-camp-asia-19/issues/4
