### ISSUE TITLE
Quantum Variational Monte Carlo (QVMC) optimisation

### ISSUE THREAD

**Issue by lmongalo** [qiskit-community/qiskit-camp-africa-19#41]
# Abstract
QVMC optimisation implimentation on Qiskit for ground state and exception energy calculations . 

# Description 
The aim of this project is to implement  QVMC optimisation on Qiskit. This can be used in chemistry applications to calculate ground state and excitations state of molecules. Other applications include optimisation in finance.

# Members

 - @lmongalo
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 

# Deliverable

# GitHub repo

**Comment by Richhy** [comment]
@lmongalo I am interested in this issue.

**Comment by IanJoel** [comment]
I am interested in this project

**Comment by AnesanR** [comment]
@lmongalo 
I would like to join to the group.

**Comment by ilsinay** [comment]
I am interested in this project

**Comment by MQubit** [comment]
I am interested in the project

**Comment by 1ucian0** [comment]
This team is moved to https://github.com/qiskit-community/qiskit-camp-africa-19/issues/15
