### ISSUE TITLE
Port MicroQiskit to a new language

### ISSUE THREAD

**Issue by quantumjim** [qiskit-community/qiskit-camp-africa-19#5]
# Abstract
[MicroQiskit](https://github.com/quantumjim/MicroQiskit/blob/master/README.md) is essentially a trial version of Qiskit, which is made available in languages other than Python 3. It contains all the basic features of writing and simulating quantum programs in Qiskit, all implemented in a minimal amount of code (~100 lines for the Python2/MicroPython/CircuitPython version). This could be ported to a new language, and a quick demo project could be made.

# Description

Current Versions:
* Python2/MicroPython/CircuitPython.
* C++ (working but unfinished).

Suggestions for ports:
* C# (to be compatible with Unity and GoDot)
* Lua (to be compatible with Minetest and Pico8)

# Members

 - Member list will be created in the comments below.
 - Qiskit Coach: @omarcostahamido 
 - Bonus Coach: @quantumjim (Coaching from afar. Available as 'James Wootton' on the Qiskit Slack. 

# Deliverable
A branch on the MicroQiskit repo with a working port.

# GitHub repo
Fork github.com/quantumjim/MicroQiskit and post a link in the comments below.

**Comment by omarcostahamido** [comment]
I would like to support this issue.
Also, this is the type of issue that could (should) have several spin off groups.
(see [My team is complete](https://github.com/qiskit-community/qiskit-camp-africa-19#team-formation))

**Comment by HuangJunye** [comment]
Please let me know if C# version will be work on. If not I'll start working on it next week.

**Comment by quantumjim** [comment]
@omarcostahamido @HuangJunye If either of you are there at the camp, and want to be a local coach (and to pitch) I cam add you in.

**Comment by omarcostahamido** [comment]
sure ;)

**Comment by HuangJunye** [comment]
Unfortunately I couldn’t go to the camp, but @omarcostahamido is there.
