### ISSUE TITLE
Classical optimizer for VQE

### ISSUE THREAD

**Issue by t-imamichi** [qiskit-community/qiskit-camp-africa-19#6]
# Abstract
Variational quantum eigensolver (VQE) is a hybrid quantum algorithm to find the ground state of an input Hamiltonian. There are several classical optimizer available in Qiskit Aqua such as SPSA and Cobyla. See the [full list](https://github.com/Qiskit/qiskit-aqua/tree/master/qiskit/aqua/components/optimizers).

Let's implement more optimizers for VQE of Aqua. There are a couples of options as follows.
- You come up with new optimization algorithms and implement them
- You look for papers about optimization of VQE and implement them, e.g., [Subspace-search variational quantum eigensolver for excited states](https://arxiv.org/abs/1810.09434)
- You look for open source libraries of optimization and integrate them into Aqua, e.g., [Optuna](https://optuna.org/), [Hyperopt](https://hyperopt.github.io/hyperopt/), and [RBFOpt](https://github.com/coin-or/rbfopt).

# Description 

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @t-imamichi

# Deliverable
- Aqua PR https://github.com/Qiskit/qiskit-aqua

# GitHub repo

**Comment by lmongalo** [comment]
Hi Im am Lehlohonolo, I am interested in this  issue

**Comment by t-imamichi** [comment]
https://github.com/qiskit-community/qiskit-camp-africa-19/issues/14 is related. Especially, If you are interested in Quantum Natural Gradient, please check it out.

**Comment by Richhy** [comment]
Hi, I am Richman. I'm interested in this project.

**Comment by Adeola80** [comment]
Hi, Ajagbe Sunday is my name, I am interested in this project
